### PR TITLE
Apply design

### PR DESCRIPTION
**Pull request by isaacmg410**
#### :tophat: What? Why?
 In this PR we apply the Blog Design

#### :pushpin: Related Issues
- Related to #1 

#### :clipboard: Subtasks
- [x] Apply design on index blog
- [x] Apply blog icon
- [x] Apply design on show blog.

### CODE REVIEW

**Comment by isaacmg410** [comment]
@decidim/lot-core someone can review it?

**Review by josepjaume — APPROVED** [review]
Nice! I like how there's no specific classes involved. Good work!

**Comment by isaacmg410** [comment]
@decidim/lot-core, ready to review.

**Review by josepjaume — APPROVED** [review]
Looks good to me!

**Comment by josepjaume** [comment]
Didn't any system spec break due to the changes?

**Comment by tramuntanal** [comment]
@decidim/lot-core @isaacmg410 isn't this PR ready?

**Comment by isaacmg410** [comment]
For me it's ready

**Pull request merged**
